#!/bin/bash

activeWinLine=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)")
activeWinId="${activeWinLine:40}"
import -window $activeWinId ~/Pictures/ScreenShoot/$(date '+%Y-%m-%d_%H:%M:%S')_screenshoot.png
dunstify -t 2500 -i ~/.config/dunst/icons/apps/ram.png "Captura de pantalla guardada"
