#!/bin/bash

if [[ ! `pidof lxpolkit` ]]; then
  dunstify -t 3000 -i ~/.config/dunst/icons/System/warning.png "STARTING POLKIT AGENT"
  nohup lxpolkit -q >/dev/null 2>&1 &
else
  dunstify -t 3500 -i ~/.config/dunst/icons/System/warning.png "AGENT POLKIT IS ACTIVE"
fi

sleep 2;

case "$1" in
    "start")
        pkexec /opt/lampp/xampp $1
        dunstify -t 3500 -i ~/.config/dunst/icons/System/update.png "SERVICIO INICIADO"
        ;;
    "stop")
        pkexec /opt/lampp/xampp $1
        dunstify -t 3500 -i ~/.config/dunst/icons/System/update.png "SERVICIO PARADO"
        ;;
    "restart")
        pkexec /opt/lampp/xampp $1
        dunstify -t 3500 -i ~/.config/dunst/icons/System/update.png "SERVICIO REINICIADO"
        ;;
    *)
        echo "Comando inválido"
        exit 1
        ;;
esac
