#!/usr/bin/env sh

xresource() {
  xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

bspc config focused_border_color  $(xresource color12)
bspc config active_border_color   "#808080"
bspc config normal_border_color   "#202020"